# config/packages/ai.yaml
ai:
    platform:
        mistral:
            api_key: '%env(MISTRAL_API_KEY)%'

    agent:
        gift_generator:
            platform: Symfony\AI\Platform\PlatformInterface
            model: 
                name: 'mistral-small-latest'
                options:
                    temperature: 0.7
                    max_tokens: 2000
                system_prompt: 'Vous étes un assistant utile et répondez en français'

